[package]
name = "gitweb"
version = "0.1.0"
authors = ["stephenwan <stephen.wan@skyscanner.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4.0"
rustyline = "6.0.0"